language: java
jdk:
  - openjdk8
before_install:
  - chmod +x mvnw
script: "./mvnw clean install"
notifications:
  email: markalbert_09@hotmail.com
deploy: :
  app: jobag-best-platform
  provider: heroku